version: "3"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
     - ./database.sql:/docker-entrypoint-initdb.d/database.sql
  web:
    build:
      context: .
      dockerfile: docker-web
    ports:
      - "8080:3000"
    depends_on:
      - db
    